### ISSUE TITLE
最后提几个问题，就不提了，用了一段时间后还是准备弃用了

### ISSUE THREAD

**Issue by hloong** [LLWenke/InteractiveChart#14]
1，BollChartModule 这个类为啥继承副指标基类，Boll这个指标和MA以及EMA都是主指标，是不是弄错？
2，EMA指标在adapter里面没有计算类，但是看到属性里面有这个，是漏掉了吗？
3，之前提过的https://github.com/LLWenke/InteractiveChart/issues/13#issuecomment-675862892 数据不全的问题
4，一般k线都是默认显示表格头部一行的MA5，MA10，MA30，长按才显示不符合逻辑

**Comment by LLWenke** [comment]
这个库只是个demo，不能保证百分之百满足你的需求，如果商用，还是有部分东西需要自定义的，EMA虽然有了类型，因为时间问题，暂时还没有开发，至于MA的显示方式，可以根据自己的需求修改，请知悉
