### ISSUE TITLE
已经同步更新，有个小问题

### ISSUE THREAD

**Issue by liweiww123** [LLWenke/InteractiveChart#17]
就是网格线会覆盖在图标之上，如图

![image](https://user-images.githubusercontent.com/12931734/104170475-24f8fb00-543c-11eb-9c32-4c36ca8e84c5.png)

试着修改FloatModule的位置， 副图和指标是可以，但是主图貌似还在网格线下面，如图
![image](https://user-images.githubusercontent.com/12931734/104170514-39d58e80-543c-11eb-8bb7-945227a16c08.png)

**Comment by LLWenke** [comment]
新的commit中已修复
