### ISSUE TITLE
你好，请问该图标库还有在维护吗？

### ISSUE THREAD

**Issue by leguang** [LLWenke/InteractiveChart#2]
你好，请问该图标库还有在维护吗？

**Comment by LLWenke** [comment]
您好，预计会在一个月左右的时间更新一个版本，将支持水印，动态指标设置等功能

leguang <notifications@github.com> 于2019年10月30日周三 上午11:25写道：

**Comment by leguang** [comment]
@LLWenke 太好了，你这个库是我看到过的这么多当中，算是比较全面的，非常感谢阁下的贡献

**Comment by LLWenke** [comment]
代码中还有许多不优雅的地方，还需要仰仗各位大佬指正呢，预计会在11月中旬推一个版本上去，修复了很多问题，也增加的一些功能

leguang <notifications@github.com> 于2019年11月1日周五 下午4:32写道：

**Comment by z876335662** [comment]
指标图能动态显示吗   动态图蜡烛图能支持动态设置宽度吗  像火币一样的  谢谢

**Comment by LLWenke** [comment]
请参照ChartLayout和BaseAttribute这两个类文件，（ChartLayout管理指标组件）（BaseAttribute管理各种属性，比如宽度，颜色，间隔等等）

cyrus <notifications@github.com> 于2019年11月12日周二 上午10:36写道：
