### ISSUE TITLE
你好  切换分钟 小时 怎么实现？

### ISSUE THREAD

**Issue by z876335662** [LLWenke/InteractiveChart#3]
你好  切换分钟 小时 怎么实现？

**Comment by LLWenke** [comment]
改变CandleAdapter中的displayType属性，您可以参照项目demo

cyrus <notifications@github.com> 于2019年11月12日周二 下午5:59写道：

**Comment by z876335662** [comment]
好的 谢谢看到了 。还有个问题 ，指标图能做成动态关闭和显示吗

**Comment by LLWenke** [comment]
现在只能是通过addDrawing和removeDrawing来控制指标显示状态，预计12月低会更新一版，到时候会支持指标动态显示和关闭


cyrus <notifications@github.com> 于2019年11月16日周六 下午3:10写道：

**Comment by z876335662** [comment]
好的 谢谢  还有问题 现在只有M20   M30能添加吗

**Comment by LLWenke** [comment]
可以的，你看看MADrawing，CandleAdapter这两个类，这里面就是控制指标的

cyrus <notifications@github.com> 于2019年11月21日周四 下午5:26写道：
