### ISSUE TITLE
第一次加载慢

### ISSUE THREAD

**Issue by z876335662** [LLWenke/InteractiveChart#4]
第一次进入视图加载慢，延迟加载
![image](https://user-images.githubusercontent.com/6060307/70109717-b61d7000-1687-11ea-9632-ac8dd6206204.png)
getRender 报 空指针

**Comment by LLWenke** [comment]
收到反馈，后一版本会修复这个问题

**Comment by will12190** [comment]
高度不要设置为0,就可以啦。因为onmeasure的时候如果为0 那么此时就是未测量完毕 那么就不会初始化onViewRectChange,那么此时mainChartModule就不会初始化
