### ISSUE TITLE
深度图显示异常 

### ISSUE THREAD

**Issue by z876335662** [LLWenke/InteractiveChart#5]
![image](https://user-images.githubusercontent.com/6060307/70675972-a7593d80-1cc5-11ea-89b0-dded77c049da.png)
![image](https://user-images.githubusercontent.com/6060307/70675992-b3dd9600-1cc5-11ea-823a-0caf271fe4f6.png)

**Comment by LLWenke** [comment]
数据要按价格升序排列，买卖深度价格不能有重叠

cyrus <notifications@github.com> 于2019年12月12日周四 上午9:56写道：

**Comment by z876335662** [comment]
![image](https://user-images.githubusercontent.com/6060307/70795044-f09ab180-1dd9-11ea-8d76-23d49011c7bb.png)
huo火币的数据成这样了

**Comment by LLWenke** [comment]
把数据截个图我看看，请截取买卖单数据都有的靠近盘口的数据区间段

cyrus <notifications@github.com> 于2019年12月13日周五 下午6:54写道：

**Comment by z876335662** [comment]
![image](https://user-images.githubusercontent.com/6060307/71088793-4f956780-21da-11ea-97a4-e1da7d7e9b44.png)
