### ISSUE TITLE
数值小于200时平均线显示异常

### ISSUE THREAD

**Issue by xulongchao1994** [LLWenke/InteractiveChart#7]
![微信图片_20200719225202](https://user-images.githubusercontent.com/26830626/87877741-a08c6900-ca12-11ea-9b44-37fdce59e7b7.jpg)
![1595170364(1)](https://user-images.githubusercontent.com/26830626/87877748-a5511d00-ca12-11ea-9473-de6cf97f330f.jpg)
直来直去  
我应该怎么修改？

**Comment by LLWenke** [comment]
更新新版code试试
